# Specify Node.js version
ARG NODE_VERSION=20.18.0

# Base image
FROM node:${NODE_VERSION}-slim as base

# Set environment and working directory
ENV NODE_ENV=development
WORKDIR /app

# Stage: Build
FROM base as build

# Copy package.json and lock file
COPY --link package.json package-lock.json ./
# Install dependencies, including Nuxt
RUN npm install

# Stage: Runtime
FROM base

# Copy dependencies from build stage
COPY --from=build /app/node_modules /app/node_modules
# Copy the application code into the container
COPY ./ ./

# Expose the development server port
EXPOSE 3000

# Default command to run Nuxt dev server
CMD [ "npm", "run", "dev" ]