# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

volumes:
  node_modules:
services:
  db:
    container_name: trail-db
    image: postgis/postgis:latest
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data

    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - ALLOW_IP_RANGE=0.0.0.0/0
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${DB_PASSWORD} pg_isready -h 127.0.0.1 -U ${DB_USER} -d gis"

  db-test:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=trail
      - POSTGRES_USER=trail
      - POSTGRES_PASSWORD=trail
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - "${TEST_DB_PORT}:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U trail -d trail"

  backend:
    container_name: trail-backend
    build:
      context: ./backend
    x-develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/.env
      environment:
        - DATABASE_URL
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:3000"
    links:
      - db

  #frontend:
    #volumes:
    #  - ./frontend:/app:cached
  #  container_name: trail-frontend
  #  build:
  #    context: ./frontend
  #    dockerfile: ./Dockerfile.dev
  #  depends_on:
  #    - backend
  #  ports:
  #    - "${FRONTEND_PORT}:3000"
  #  environment:
  #    HOST: 0.0.0.0
  #    PORT: 3000
  #    BACKEND_URL: http://backend:3000
  #  ulimits:
  #    nofile:
  #      soft: 8192
  #0      hard: 8192
