name: Code Quality

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

        db-name:
          - e2e-testing-db
        db-user:
          - user
        db-password:
          - password
        db-host:
          - localhost
        db-port:
          - 5432
    services:
      postgis:
        image: postgis/postgis:latest
        env:
          POSTGRES_DB: ${{ matrix.db-name }}
          POSTGRES_USER: ${{ matrix.db-user }}
          POSTGRES_PASSWORD: ${{ matrix.db-password }}
        ports:
          - ${{ matrix.db-port }}:${{ matrix.db-port }}
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        # v3 does not work with act, don't know why...
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint

      - name: Run the unit tests
        run: npm run test:unit:cov

      - name: Prepare database schema for e2e test
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://${{ matrix.db-user }}:${{ matrix.db-password }}@${{ matrix.db-host }}:${{ matrix.db-port }}/${{ matrix.db-name }}?schema=public

      - name: Run the e2e tests
        run: npm run test:e2e:cov
        env:
          DATABASE_URL: postgresql://${{ matrix.db-user }}:${{ matrix.db-password }}@${{ matrix.db-host }}:${{ matrix.db-port }}/${{ matrix.db-name }}?schema=public
